# Generated by Django 2.1.5 on 2019-01-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Humitidty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='tempreture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temprature', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('change', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
            ],
        ),
    ]
