# Generated by Django 2.1.5 on 2019-01-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celesius', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('change', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
            ],
        ),
        migrations.DeleteModel(
            name='tempreture',
        ),
    ]
