# Generated by Django 2.1.5 on 2019-01-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190123_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='celesius',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='change',
            field=models.FloatField(default=0.0),
        ),
    ]
