# Generated by Django 2.1.5 on 2019-04-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_temperature_recorded_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Humidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RH', models.FloatField(default=0.0)),
                ('change', models.FloatField(default=0.0)),
                ('recorded_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BP', models.FloatField(default=0.0)),
                ('change', models.FloatField(default=0.0)),
                ('recorded_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Humitidty',
        ),
    ]
